name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.56.0]
        features: ['', 'releasefast', 'slot_u32', 'slot_u64', 'slot_usize']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    
    - name: Build
      run: cargo build --verbose --features ${{ matrix.features }}
    
    - name: Run tests
      run: cargo test --verbose --features ${{ matrix.features }}
    
    - name: Run clippy
      run: cargo clippy --verbose --features ${{ matrix.features }} -- -D warnings
    
    - name: Check formatting
      run: cargo fmt --check

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust with Miri
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: miri
    
    - name: Run tests with Miri
      run: cargo miri test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    
    - name: Check documentation
      run: cargo doc --no-deps --document-private-items
      env:
        RUSTDOCFLAGS: -D warnings